version: "3.8"
services:
  backend:
    build: ./back-end
    image: swiftbuy-backend-image
    container_name: swiftbuy-backend-container
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
  frontend:
    build: ./front-end
    image: swiftbuy-frontend-image
    container_name: swiftbuy-frontend-container
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
